### ISSUE TITLE
Is there any way to detect connection fail?

### ISSUE THREAD

**Issue by supermomonga** [emiln/slacker#49] opened 2016-06-18 23:41 UTC
While Slack API is working normally, I can use `slacker.client/connect-bot` function and `:bot-disconnected` event to connect/re-connect to the slack API.

The problem is, when Slack API is down, [`slacker.client/connect-bot` only will put the message to the logger and won't emit any event](https://github.com/emiln/slacker/blob/47d17119e24a6879c6095420cfddde141f4cc5cd/src/slacker/client.clj#L97).

When `slacker.client/connect-bot` failed, I want to retry after put some wait time. Is there any way to detect connection fail?

**Comment by emiln** [comment] 2016-06-19 08:56
That's a good point. It should definitely emit an event detailing the error that occurred. I haven't put a lot of thought into a good scheme for naming error events, but perhaps something like `::connect-bot-error` or `:connect-bot-failed`. It'll take a minor rewrite to pass along the actual error that occurred, which is the only way to make it useful, I think.

I'll see if I can fit in a quick fix this weekend.

**Comment by supermomonga** [comment] 2016-06-19 18:35
> It'll take a minor rewrite to pass along the actual error that occurred, which is the only way to make it useful, I think.

Ah, I agree with that. It sounds handy.

> I'll see if I can fit in a quick fix this weekend.

Thanks! Take your time, please 😄

**Comment by supermomonga** [comment] 2016-06-24 06:11
I'm planning to close this issue after new version bumped on clojars.

**Comment by emiln** [comment] 2016-06-24 10:12
Cool. I'll have it on clojars during this weekend I imagine.

**Comment by emiln** [comment] 2016-06-24 22:16
It should be [on clojars](https://clojars.org/emiln/slacker). You can close the issue if it's solved with the new version. :smiley:

**Comment by supermomonga** [comment] 2016-06-25 07:58
Thank you! I'll try with latest version, and maybe it takes few days to confirm that event emitted when Slack API is down.

**Comment by emiln** [comment] 2016-07-15 10:52
Hey, @supermomonga. I'm taking the liberty of closing this issue for now. If it turns out the issue isn't actually solved, you can just reopen it again.

**Closed as completed by emiln** 2016-07-15 10:52 UTC
